
Erros e exceções podem levar à falha do programa ou a um comportamento inesperado, e o Python vem com um conjunto robusto de ferramentas para melhorar a estabilidade do código.


Um erro é um problema em um programa que o impede de concluir sua tarefa. Em comparação, uma exceção é uma condição que interrompe o fluxo normal do programa. Tanto os erros quanto as exceções são um tipo de erro de tempo de execução, o que significa que ocorrem durante a execução de um programa. 

Em palavras simples, o erro é um problema crítico que um aplicativo normal não deve detectar, enquanto uma exceção é uma condição que um programa deve detectar.

## Tratamento de exceções

É possível escrever programas que tratam exceções específicas.

### Exemplo:

```python
while True:
    try:
        x = int(input("Insira um número: "))
        break
    except ValueError:
        print("Ops! Esse não é um número válido. Tente novamente...")
```

A instrução [`try`](https://docs.python.org/pt-br/3.13/reference/compound_stmts.html#try) funciona da seguinte maneira:

- Primeiramente, a _cláusula try_ (o conjunto de instruções entre as palavras reservadas [`try`](https://docs.python.org/pt-br/3.13/reference/compound_stmts.html#try) e [`except`](https://docs.python.org/pt-br/3.13/reference/compound_stmts.html#except) ) é executada.
    
- Se nenhuma exceção ocorrer, a _cláusula except_ é ignorada e a execução da instrução [`try`](https://docs.python.org/pt-br/3.13/reference/compound_stmts.html#try) é finalizada.
    
- Se ocorrer uma exceção durante a execução de uma cláusura [`try`](https://docs.python.org/pt-br/3.13/reference/compound_stmts.html#try), as instruções remanescentes na cláusula são ignoradas. Se o tipo da exceção ocorrida tiver sido previsto em algum [`except`](https://docs.python.org/pt-br/3.13/reference/compound_stmts.html#except), essa _cláusura except_ é executada, e então depois a execução continua após o bloco try/except.
    
- Se a exceção levantada não corresponder a nenhuma exceção listada na _cláusula de exceção_, então ela é entregue a uma instrução [`try`](https://docs.python.org/pt-br/3.13/reference/compound_stmts.html#try) mais externa. Se não existir nenhum tratador previsto para tal exceção, trata-se de uma _exceção não tratada_ e a execução do programa termina com uma mensagem de erro.
-
